VIH-9557 Updated yaml and csproj azure function version
hmcts/vh-booking-queue-subscriber pull request #120
Opened 2022-12-14 18:52 UTC by will-craig

### JIRA link (if applicable) ###
[VIH-9557](https://tools.hmcts.net/jira/browse/VIH-9557)

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[X] No
```

2022-12-14 19:07 UTC, oliver-scott approved these changes

2022-12-15 09:34 UTC, oliver-scott approved these changes

2022-12-15 09:35 UTC, v1ferrarij requested changes
need the helm charts in this PR as it is not working in SDS

2022-12-15 09:39 UTC, v1ferrarij approved these changes

2022-12-15 09:39 UTC, merged